*ОТЧЕТ ПО ЛАБОАТОРНОЙ РАБОТЕ №1

= *ЗАДАНИЕ 1*
* В среде разработки IAR Embedded Workbench необходимо создать  проект C++ c main.СРР.

Для того, что бы содать проект нам необходимо нажать Project>Create New Project.

Затем выбираем язык C++ и функцию main и сохраняем в формате Project Files (*.ewp).

*  Теперь необходимо выбрать микроконтроллер, с которым мы будем работать. Для этого необходимо перейти во вкладку Options for node " " > General Options > Target > Device > ST >STM32F4 > STM32F411 > STM32F411RE.

*  Теперь необходимо подключить к проекту файл cstartup.CPP

Для этого в превую очередб необходимо скачать этот файл.  псле того, как скачали  переходим обратно в IAR Embedded Workbench.

Нажимаем Add > Add Files > startup_stm32F411.СРР
После добавления всех папок у нас должна получиться, так называемая иерархическая структура.

* Теперь необходимо настроить STACK, HEAP.

Переходим во вкладку Options for node " " > Linker > Advanced > Enable stack usage analysis (ставим галочку).

* 5. Теперь пишем код main (копируем готовый код из задания) и копилируем. 

  #include "gpiocregisters.hpp" //for GPIOC
  #include "rccregisters.hpp"   //for RCC

  int main()
  {
    RCC::AHB1ENR::GPIOCEN::Enable::Set() ;
    GPIOC::MODER::MODER5::Output::Set() ;
    GPIOC::ODR::ODR5::Enable::Set() ;
    GPIOC::ODR::ODR5::Disable::Set() ;
    return 0 ;
  }
  
  
  
Код не скомпилирован. Возникили ошибки. Для их устранения необходимо поменять значения регистра ODR5. Устанавливаем " Enable" и "Outputy".
Теперь все работает и диоды на плате мигают.

= *ЗАДАНИЕ 2*

* Теперь нам необходимо прошить программу в микроконтроллер.

Для того, что бы откомпилировать и отлинковать программу восмользуемся командой make. Программа откопилирована. Ошибок нет. 

* Теперь запустим программу в симуляторе. Для этого нажимаем Download and Debug и производим пошаговую отладку, нажимая на клавишу F10.

Необходимо настроить Debugger на отладку через StLink.

Для этого нажимем Project > Options . St-Link> в окне Interface ставим галочку на SWD.

* Теперь загружаем программу в плату. Нажимаем Ctrl+D и задаем пусть к файлу. После этого выполняем отладку в плате (пошаговая отладка выполняется так же клавишей F10)

На плате загорается диод. Все работает. 

= *ЗАДАНИЕ 3*

* Запускаем анализ стека в настройке. В .map файле смотрим рекомендуемый размер стека, в данном случае - 16. И меняем размер стека на 16.

* .map файл-это текстовый файл, в котором находистя таблица адресов. 
В .map файле описаны размеры составляющих (размер стека, размер отдельных элементов и размер файла).


* Поставить размер кучи HEAP в 0 возможно, потому что не используется динамическая память. А размер STACK 0 нельзя поставить, так как при использовании функций будет невозможна запись адреса возврата.
 
 
 
